name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Compiling the code..."
          echo "Compile complete."

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        job: [unit, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ${{ matrix.job }} tests
        run: |
          if [ "${{ matrix.job }}" = "unit" ]; then
            echo "Running unit tests... This will take about 60 seconds."
            sleep 1
            echo "Code coverage is 90%"
          elif [ "${{ matrix.job }}" = "lint" ]; then
            echo "Linting code... This will take about 10 seconds."
            sleep 1
            echo "No lint issues found."
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure
        run: |
          echo "Deploying application..."
          echo "Application successfully deployed."
